cmdb/urls.py
from django.conf.urls import url, include


urlpatterns = [
    url(r'^api/', include('cmdb_api.urls', namespace='api', app_name='cmdb_api')),
    url(r'^', include('cmdb_ui.urls', namespace='cmdb', app_name='cmdb_ui'))
]

cmdb_ui/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^asset_list/(?P<page_num>[0-9]+)?/?$', asset_list, name='asset_list'),
    url(r'^asset_add_server/$', asset_add_server, name='asset_add_server'),
    url(r'^asset_add_networkdevice/$', asset_add_networkdevice, name='asset_add_networkdevice'),
    url(r'^asset_edit_server/(?P<asset_id>[0-9]+)/$', asset_edit_server, name='asset_edit_server'),
    url(r'^asset_edit_networkdevice/(?P<asset_id>[0-9]+)/$', asset_edit_networkdevice, name='asset_edit_networkdevice'),
    url(r'^asset_detail/(?P<asset_id>[0-9]+)/$', asset_detail, name='asset_detail'),
    url(r'^object_query/$', object_query, name='object_query'),

    url(r'^idc_list/(?P<page_num>[0-9]+)?/?$', idc_list, name='idc_list'),
    url(r'^idc_add/$', idc_add, name='idc_add'),
    url(r'^idc_edit/(?P<idc_id>[0-9]+)/$', idc_edit, name='idc_edit'),
    url(r'^idc_diagram/(?P<idc_id>[0-9]+)/$', idc_diagram, name='idc_diagram'),

    url(r'^user_list/(?P<page_num>[0-9]+)?/?$', user_list, name='user_list'),
    url(r'^user_add/$', user_add, name='user_add'),
    url(r'^user_edit/(?P<user_id>[0-9]+)/$', user_edit, name='user_edit'),
    url(r'^user_detail/(?P<user_id>[0-9]+)/$', user_detail, name='user_detail'),

    url(r'^business_line_list/(?P<page_num>[0-9]+)?/?$', business_line_list, name='business_line_list'),
    url(r'^business_line_add/$', business_line_add, name='business_line_add'),
    url(r'^business_line_edit/(?P<business_line_id>[0-9]+)/$', business_line_edit, name='business_line_edit'),
    url(r'^business_line_detail/(?P<business_line_id>[0-9]+)/$', business_line_detail, name='business_line_detail'),

]

cmdb_ui/forms.py
from django import forms
from cmdb.models import (Asset, User, Server, NetworkDevice,
                         AssetGroup, AssetType, UserGroup, IDC)


class AssetForm(forms.ModelForm):
    usergroup = forms.ModelChoiceField(queryset=UserGroup.objects.all(),
                                       widget=forms.SelectMultiple)

    class Meta:
        model = Asset
        exclude = ('create_time', 'update_time')


class ServerForm(forms.ModelForm):
    class Meta:
        model = Server
        exclude = ('asset', )


class NetworkDeviceForm(forms.ModelForm):
    class Meta:
        model = NetworkDevice
        exclude = ('asset', )


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'realname', 'password', 'email', 'mobile', 'usergroup']


class AssetGroupForm(forms.ModelForm):
    class Meta:
        model = AssetGroup
        fields = ['groupname', 'comment']


class AssetTypeForm(forms.ModelForm):
    class Meta:
        model = AssetType
        fields = ['name', 'comment']


class UserGroupForm(forms.ModelForm):
    class Meta:
        model = UserGroup
        fields = ['groupname', 'assetgroup']


class IDCForm(forms.ModelForm):
    class Meta:
        model = IDC
        fields = ['name', 'comment']

cmdb_ui/views.py
# coding = utf-8
#

import json
from collections import ChainMap
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse, Http404
from django.views.decorators.csrf import csrf_exempt, ensure_csrf_cookie
from django.core.urlresolvers import reverse
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q, Count
# from django.contrib.auth import authenticate
from cmdb.models import (User, Asset, IDC, History, BusinessLine, NetworkInterface, Memory, CPU,
                         HWSystem, Disk)
from cmdb_api.utils import encrypt_pwd
from .utils import (require_login, get_username, clean_server_form_data, pages, clean_form_data,
                    clean_networkdevice_form_data, Cabinet)
from cmdb_api.serializers import (ServerAssetCreateUpdateSerializer, NetDeviceAssetCreateUpdateSerializer,
                                  IDCSerializer, UserSerializer, BusinessLineSerializer)
# from .forms import UserForm, AssetForm, ServerForm, NetworkDeviceForm
from datetime import datetime
from urllib.parse import urlencode
# Create your views here.


@ensure_csrf_cookie
@require_login
def index(request):
    username, realname = get_username(request.session['uid'])

    user_number = User.objects.count()
    assets_number = Asset.objects.count()
    vhosts_number = Asset.objects.filter(Q(asset_type='虚拟机') | Q(asset_type='云主机')).count()
    phosts_number = Asset.objects.filter(asset_type='服务器').count()

    idc_number = IDC.objects.count()

    if username and realname:
        return render(request, 'statistics.html', locals())
    return HttpResponseRedirect(reverse('cmdb_ui:login'))


@csrf_exempt
def login(request):
    if request.method == 'POST':
        user = User.objects.filter(username=request.POST.get('username', '')).first()
        if not user:
            return JsonResponse({'status': 404})

        if encrypt_pwd(request.POST.get('password', '')) == user.password:
            request.session['username'] = user.username
            request.session['uid'] = user.id
            return JsonResponse({'status': 200, 'url': reverse('cmdb_ui:index')})
        return JsonResponse({'status': 400})
    return render(request, 'login.html')


@require_login
def logout(request):
    request.session.flush()
    response = HttpResponseRedirect(reverse('cmdb_ui:login'))
    response.delete_cookie('csrftoken')
    return response


@require_login
def asset_list(request, page_num):
    username, realname = get_username(request.session['uid'])
    servers = ('服务器', '云主机', '虚拟机')

    # delete operation
    if request.method == 'POST':
        ids = request.POST.get('ids')
        if ids is None:
            return JsonResponse({'code': 400, 'msg': 'request error, not receive any data'},
                                status=400)
        try:
            idlist = [int(i) for i in json.loads(ids)]
            Asset.objects.filter(id__in=idlist).delete()
        except Exception as e:
            return JsonResponse({'code': 500, 'msg': str(e)}, status=500)
        return JsonResponse({'code': 200, 'msg': 'delete ok'}, status=200)

    # search and list
    page_total_item_num = 30
    if page_num is None:
        page_num = 1

    params, keyword = None, request.GET.get('keyword', None)

    if len(request.GET) != 0 and 'keyword' not in request.GET:
        params = urlencode(request.GET)

    if params is not None:
        queryset = Asset.objects.all()

        if 'idc' in request.GET:
            # print('idc', request.GET['idc'])
            queryset = queryset.filter(idc__name=request.GET['idc'])
            # print(queryset)
        if 'asset_type' in request.GET:
            # print('asset_type', request.GET['asset_type'])
            queryset = queryset.filter(asset_type=request.GET['asset_type'])
        if 'business_line' in request.GET:
            queryset = queryset.filter(business_line__name=request.GET['business_line'])
        if 'contact' in request.GET:
            queryset = queryset.filter(contact__realname=request.GET['contact'])
            # print(queryset)
        if 'cabinet_number' in request.GET:
            queryset = queryset.filter(cabinet_number=int(request.GET['cabinet_number']))

        start, end, page_html = pages(queryset, page_num, '/asset_list',
                                      page_total_item_num, params=params)

    elif keyword is not None:
        queryset = Asset.objects.filter(Q(server__hostname__contains=keyword) |
                                        Q(server__lan_ip__contains=keyword) |
                                        Q(networkdevice__name__contains=keyword))
        params = urlencode({'keyword': keyword})
        start, end, page_html = pages(queryset, page_num, '/asset_list',
                                      page_total_item_num, params=params)
    else:
        queryset = Asset.objects.all()
        start, end, page_html = pages(queryset, page_num, '/asset_list',
                                      page_total_item_num)
    assets = queryset[start:end]
    return render(request, 'asset_list.html', locals())


@require_login
def object_query(request):
    field = request.POST.get('field')
    if field == 'idc':
        return JsonResponse({'data': [i.name for i in IDC.objects.all()]})
    elif field == 'business_line':
        return JsonResponse({'data': [i.name for i in BusinessLine.objects.all()]})
    elif field == 'contact':
        return JsonResponse({'data': [i.realname for i in User.objects.all()]})
    elif field == 'asset_type':
        types = Asset.objects.values('asset_type').annotate(Count('asset_type'))
        return JsonResponse({'data': [i['asset_type'] for i in types]})
    elif field == 'cabinet_number':
        numbers = Asset.objects.values('cabinet_number').annotate(Count('cabinet_number'))
        return JsonResponse({'data': [i['cabinet_number'] for i in numbers if i['cabinet_number'] is not None]})


@require_login
def asset_add_server(request):
    username, realname = get_username(request.session['uid'])
    idcs = IDC.objects.order_by('id')
    users = User.objects.order_by('id')
    business_line = BusinessLine.objects.order_by('id')

    if request.method == 'POST':
        data, errors = clean_server_form_data(request, Asset)
        if errors is not None:
            hidden_success = 'hidden'
            return render(request, 'asset_add_server.html', locals())

        data.pop('csrfmiddlewaretoken')
        serial = ServerAssetCreateUpdateSerializer(data=data)
        if serial.is_valid():
            serial.save()
            hidden_failed = 'hidden'
            return render(request, 'asset_add_server.html', locals())
        hidden_success, errors = 'hidden', serial.errors
        return render(request, 'asset_add_server.html', locals())

    hidden_failed = hidden_success = 'hidden'
    return render(request, 'asset_add_server.html', locals())


@require_login
def asset_add_networkdevice(request):
    username, realname = get_username(request.session['uid'])
    idcs = IDC.objects.order_by('id')
    users = User.objects.order_by('id')
    business_line = BusinessLine.objects.order_by('id')

    if request.method == 'POST':
        data, errors = clean_networkdevice_form_data(request, Asset)
        if errors is not None:
            hidden_success = 'hidden'
            return render(request, 'asset_add_networkdevice.html', locals())

        data.pop('csrfmiddlewaretoken')
        serial = NetDeviceAssetCreateUpdateSerializer(data=data)
        if serial.is_valid():
            serial.save()
            hidden_failed = 'hidden'
            return render(request, 'asset_add_networkdevice.html', locals())
        hidden_success, errors = 'hidden', serial.errors
        return render(request, 'asset_add_networkdevice.html', locals())

    hidden_failed = hidden_success = 'hidden'
    return render(request, 'asset_add_networkdevice.html', locals())


@require_login
def asset_edit_server(request, asset_id):
    username, realname = get_username(request.session['uid'])
    idcs = IDC.objects.order_by('id')
    users = User.objects.order_by('id')
    business_line = BusinessLine.objects.order_by('id')

    try:
        pk = int(asset_id)
        asset = Asset.objects.get(pk=pk)
        networkinterface = NetworkInterface.objects.filter(server=asset.server.id).order_by('name')
        memory = Memory.objects.filter(server=asset.server.id)
        cpu = CPU.objects.filter(server=asset.server.id).order_by('socket')
        disk = Disk.objects.filter(server=asset.server.id)
        hw_system = HWSystem.objects.filter(server=asset.server.id).first()
    except (ValueError, ObjectDoesNotExist) as e:
        hidden_success, errors = 'hidden', str(e)
        return render(request, 'asset_edit_server.html', locals())

    if request.method == 'POST':
        # print(request.POST.get('asset_type'))
        data, errors = clean_server_form_data(request, Asset)
        if errors is not None:
            hidden_success = 'hidden'
            return render(request, 'asset_edit_server.html', locals())

        data.pop('csrfmiddlewaretoken')
        serial = ServerAssetCreateUpdateSerializer(asset, data=data)
        if serial.is_valid():
            serial.save()
            hidden_failed = 'hidden'
            return render(request, 'asset_edit_server.html', locals())
        hidden_success, errors = 'hidden', serial.errors
        return render(request, 'asset_edit_server.html', locals())

    hidden_failed = hidden_success = 'hidden'
    return render(request, 'asset_edit_server.html', locals())


@require_login
def asset_edit_networkdevice(request, asset_id):
    username, realname = get_username(request.session['uid'])
    idcs = IDC.objects.order_by('id')
    users = User.objects.order_by('id')
    business_line = BusinessLine.objects.order_by('id')

    try:
        pk = int(asset_id)
        asset = Asset.objects.get(pk=pk)

cmdb_ui/templates/asset_list.html
{% extends "layout.html" %}
{% load my_tags %}
{% load static %}

{% block link-css %}
    <link rel="stylesheet" href="{% static 'css/list.css' %}" />
{% endblock %}

{% block navbar %}
    <li>资产管理</li>
    <li class="active">资产列表</li>
{% endblock %}

{% block content %}
    <div class="alert alert-danger offset-left-2 hidden" role="alert">所选资产删除失败 ! !</div>
    <div class="alert alert-success offset-left-2 hidden" role="alert">已成功删除所选资产 ! !</div>
    <!-- 当前页展示 -->
    <div class="content">
        <div class=" content-header">
            <h3 style="text-indent: 20px; width: 150px; float: left;">资产列表</h3>
            <button class="btn btn-sm btn-primary advance-search">高级搜索</button>
            <div class="advance-search-obj hidden" id="advance-search-example">
                <select name="field" class="field">
                    <option value=""></option>
                    <option value="asset_type">资产类型</option>
                    <option value="idc">机房</option>
                    <option value="business_line">业务线</option>
                    <option value="cabinet_number">机柜号</option>
                    <option value="contact">负责人</option>
                </select>
                <select name="value" class="value">
                    <option value=""></option>
                </select>
{#                <input type="text"  class="form-control input-value">#}
            </div>

            <div class="advance-search-obj">
                <select name="field" class="field">
                    <option value=""></option>
                    <option value="asset_type">资产类型</option>
                    <option value="idc">机房</option>
                    <option value="business_line">业务线</option>
                    <option value="cabinet_number">机柜号</option>
                    <option value="contact">负责人</option>
                </select>
                <select name="value" class="value">
                    <option value=""></option>
                </select>
{#                <input type="text"  class="form-control input-value">#}
            </div>
            <button class="btn-sm btn btn-default advance-search-add">+</button>
        <div class="clearfix"></div>
        </div>

        <div class="content-op">
            <a href="{% url 'cmdb_ui:asset_add_server' %}" class="btn btn-success btn-sm btn-asset-position">添加资产</a>
            <button type="button" id="deletion-selected" class="btn btn-sm btn-danger" data-toggle="modal">删除所选</button>

            <div class="search">
                <div class="input-group search-width">
                    <input id="search-input" type="text" class="form-control" placeholder="ip or hostname">
                    <span class="input-group-btn">
                        <button class="btn btn-info" type="button">Search</button>
                    </span>
                </div>
            </div>
        </div>

        <div class="table-page table-responsive">
            <table class="table table-hover table-striped" style="margin-bottom: -8px;">
                <thead>
                    <tr>
                        <th class="text-center">
                            <input id="checkall" type="checkbox" name="checkall" value="checkall" >
                        </th>
                        <th>资产类型</th>
                        <th>内网IP</th>
                        <th>外网IP</th>
                        <th>业务线</th>
                        <th>机房</th>
                        <th>系统</th>
                        <th>内存</th>
                        <th>磁盘</th>
                        <th>用途</th>
                        <th>负责人</th>
                        <th>状态</th>
                        <th>操作</th>
                    </tr>
                </thead>

                <tbody>
                    {% for asset in assets %}
                    {% if asset.state == 0 %}
                    <tr data-id="{{ asset.id }}" class="item-offline">
                    {% else %}
                    <tr data-id="{{ asset.id }}">
                    {% endif %}
                        <td class="text-center">
                            <input type="checkbox" name="assetid" value="{{ asset.id }}">
                        </td>
                        <td>{{ asset.asset_type }}</td>
                        {% if asset.asset_type in servers %}
                            <td>{{ asset.server.lan_ip }}</td>
                            <td>{{ asset.server.wan_ip | default_if_none:"" }}</td>
                        {% else %}
                            <td>{{ asset.networkdevice.ip | default_if_none:"" }}</td>
                            <td>{{ asset.networkdevice.mac | default_if_none:"" }}</td>
                        {% endif %}
                        <td>{{ asset | get_business_line | join:"、" }}</td>
                        <td>{{ asset.idc.name }}</td>
                        {% if asset.asset_type in servers %}
                            <td>{{ asset.server.os }}</td>
                            <td>{{ asset.server.logical_memory }}</td>
                            <td>{{ asset.server.logical_disk }}</td>
                        {% else %}
                            <td></td>
                            <td></td>
                            <td></td>
                        {% endif %}
                        <td>{{ asset.use }}</td>
                        <td>{{ asset.contact.realname }}</td>
                        {% if asset.state == 1 %}
                        <td><button type="button" class="btn btn-xs btn-success">在线</button></td>
                        {% else %}
                        <td><button type="button" class="btn btn-xs btn-default btn-gray">下线</button></td>
                        {% endif %}
                        <td>
                            <a href="{% url 'cmdb_ui:asset_detail' asset_id=asset.id %}" class="btn btn-xs btn-primary">详情</a>
                            {% if asset.asset_type in servers %}
                            <a href="{% url 'cmdb_ui:asset_edit_server' asset_id=asset.id %}" class="btn btn-xs btn-info">修改</a>
                            {% else %}
                            <a href="{% url 'cmdb_ui:asset_edit_networkdevice' asset_id=asset.id %}" class="btn btn-xs btn-info">修改</a>
                            {% endif %}
                            <button type="button" class="btn btn-xs btn-danger" data-toggle="modal">删除</button>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

            <!-- 警告模态框 -->
            <div class="modal fade" id="alert-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
              <div class="modal-dialog modal-sm" role="document">
                <div class="modal-content">
                    <div class="modal-header"><h4 style="color: orangered; text-align: center;">警告</h4></div>
                    <div class="modal-body"><h5 style="text-align: center;">确定要删除所选资产? 此操作不可逆</h5></div>
                    <div class="modal-footer">
                        <button type="button" id="btn-modal-yes" class="btn btn-danger">删除</button>
                        <button type="button" class="btn btn-primary" data-dismiss="modal">取消</button>
                    </div>
                </div>
              </div>
            </div>

            <!-- 分页 -->
            <nav aria-label="Page navigation" style="float: right;">
                <ul class="pagination">
{#                    <li><a href="#" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>#}
{#                    <li><a href="{% url 'cmdb_ui:asset_list' page_num=1 %}">1</a></li>#}
                    {{ page_html }}
{#                    <li><a href="#" aria-label="Next"><span aria-hidden="true">&raquo;</span></a></li>#}
                </ul>
            </nav>
        </div>
    </div>
{% endblock %}


{% block JavaScripts %}
    <script type="text/javascript" src="{% static 'js/common.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/list.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/list_asset.js' %}"></script>
{% endblock %}



cmdb_ui/templates/assetgroup_list.html
{% extends "layout.html" %}
{% load my_tags %}
{% load static %}

{% block link-css %}
    <link rel="stylesheet" href="{% static 'css/list.css' %}" />
{% endblock %}

{% block navbar %}
    <li>资产管理</li>
    <li class="active">查看资产组</li>
{% endblock %}

{% block content %}
    <div class="alert alert-danger offset-left-2 hidden" role="alert">所选资产组删除失败 ! !</div>
    <div class="alert alert-success offset-left-2 hidden" role="alert">已成功删除所选资产组 ! !</div>
    <!-- 当前页展示 -->
    <div class="content">
        <div class=" content-header">
            <h3 style="text-indent: 20px;">查看资产组</h3>
        </div>

        <div class="content-op">
            <a href="{% url 'cmdb_ui:assetgroup_add' %}" class="btn btn-success btn-sm btn-asset-position">添加资产组</a>
            <button type="button" id="deletion-selected" class="btn btn-sm btn-danger" data-toggle="modal">删除所选</button>

            <div class="search">
                <div class="input-group search-width">
                    <input id="search-input" type="text" class="form-control" placeholder="group name">
                    <span class="input-group-btn">
                        <button class="btn btn-info" type="button">Search</button>
                    </span>
                </div>
            </div>
        </div>

        <div class="table-page table-responsive">
            <table class="table table-bordered" style="margin-bottom: -8px;">
                <thead>
                    <tr>
                        <th class="text-center">
                            <input id="checkall" type="checkbox" name="checkall" value="checkall" >
                        </th>
                        <th>组名</th>
                        <th>拥有主机数</th>
                        <th>所属用户组/项目组</th>
                        <th>注释</th>
                        <th>操作</th>
                    </tr>
                </thead>

                <tbody>
                    {% for ag in assetgroups %}
                    <tr data-id="{{ ag.id }}">
                        <td class="text-center">
                            <input type="checkbox" name="assetgroupid" value="{{ ag.id }}">
                        </td>
                        <td>{{ ag.groupname }}</td>
                        <td>{{ ag | servers_count }}</td>
                        <td>{{ ag | fetch_aggroup_name | join:"、" }}</td>
                        <td>{{ ag.comment | default_if_none:"" }}</td>

                        {% if ag.groupname == '默认' %}
                        <td>
                            <a href="#" class="btn btn-xs btn-success">详情</a>
                            <a href="#" class="btn btn-xs btn-info" disabled>编辑</a>
                            <button type="button" class="btn btn-xs btn-danger" data-toggle="modal" disabled>删除</button>
                        </td>
                        {% else %}
                         <td>
                            <a href="#" class="btn btn-xs btn-success">详情</a>
                            <a href="{% url 'cmdb_ui:assetgroup_edit' assetgroup_id=ag.id %}" class="btn btn-xs btn-info">编辑</a>
                            <button type="button" class="btn btn-xs btn-danger" data-toggle="modal">删除</button>
                        </td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

            <!-- 警告模态框 -->
            <div class="modal fade" id="alert-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
              <div class="modal-dialog modal-sm" role="document">
                <div class="modal-content">
                    <div class="modal-header"><h4 style="color: orangered; text-align: center;">警告</h4></div>
                    <div class="modal-body"><h5 style="text-align: center;">确定要删除所选资产组? 此操作不可逆</h5></div>
                    <div class="modal-footer">
                        <button type="button" id="btn-modal-yes" class="btn btn-danger">删除</button>
                        <button type="button" class="btn btn-primary" data-dismiss="modal">取消</button>
                    </div>
                </div>
              </div>
            </div>

            <!-- 分页 -->
            <nav aria-label="Page navigation" style="float: right;">
                <ul class="pagination">
{#                    <li><a href="#" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>#}
{#                    <li><a href="{% url 'cmdb_ui:asset_list' page_num=1 %}">1</a></li>#}
                    {{ page_html }}
{#                    <li><a href="#" aria-label="Next"><span aria-hidden="true">&raquo;</span></a></li>#}
                </ul>
            </nav>
        </div>
    </div>
{% endblock %}


{% block JavaScripts %}
    <script type="text/javascript" src="{% static 'js/common.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/list.js' %}"></script>
{% endblock %}



cmdb_ui/templates/business_line_list.html
{% extends "layout.html" %}
{% load my_tags %}
{% load static %}

{% block link-css %}
    <link rel="stylesheet" href="{% static 'css/list.css' %}" />
{% endblock %}

{% block navbar %}
    <li>业务管理</li>
    <li class="active">查看业务线</li>
{% endblock %}

{% block content %}
    <div class="alert alert-danger offset-left-2 hidden" role="alert">所选业务线删除失败 ! !</div>
    <div class="alert alert-success offset-left-2 hidden" role="alert">已成功删除所选业务线 ! !</div>
    <!-- 当前页展示 -->
    <div class="content">
        <div class=" content-header">
            <h3 style="text-indent: 20px;">查看业务线</h3>
        </div>

        <div class="content-op">
            <a href="{% url 'cmdb_ui:business_line_add' %}" class="btn btn-success btn-sm btn-asset-position">添加业务线</a>
            <button type="button" id="deletion-selected" class="btn btn-sm btn-danger" data-toggle="modal">删除所选</button>

            <div class="search">
                <div class="input-group search-width">
                    <input id="search-input" type="text" class="form-control" placeholder="业务线">
                    <span class="input-group-btn">
                        <button class="btn btn-info" type="button">Search</button>
                    </span>
                </div>
            </div>
        </div>

        <div class="table-page table-responsive">
            <table class="table table-bordered" style="margin-bottom: -8px;">
                <thead>
                    <tr>
                        <th class="text-center">
                            <input id="checkall" type="checkbox" name="checkall" value="checkall" >
                        </th>
                        <th>业务线</th>
                        <th>注释</th>
                        <th>操作</th>
                    </tr>
                </thead>

                <tbody>
                    {% for bn in business_line %}
                    <tr data-id="{{ bn.id }}">
                        <td class="text-center">
                            <input type="checkbox" name="business_line_id" value="{{ bn.id }}">
                        </td>
                        <td>{{ bn.name }}</td>
                        <td>{{ bn.comment | default_if_none:"" }}</td>

                         <td>
{#                            <a href="#" class="btn btn-xs btn-success">详情</a>#}
                            <a href="{% url 'cmdb_ui:business_line_edit' business_line_id=bn.id %}" class="btn btn-xs btn-info">编辑</a>
                            <button type="button" class="btn btn-xs btn-danger" data-toggle="modal">删除</button>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

            <!-- 警告模态框 -->
            <div class="modal fade" id="alert-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
              <div class="modal-dialog modal-sm" role="document">
                <div class="modal-content">
                    <div class="modal-header"><h4 style="color: orangered; text-align: center;">警告</h4></div>
                    <div class="modal-body"><h5 style="text-align: center;">确定要删除所选资产组? 此操作不可逆</h5></div>
                    <div class="modal-footer">
                        <button type="button" id="btn-modal-yes" class="btn btn-danger">删除</button>
                        <button type="button" class="btn btn-primary" data-dismiss="modal">取消</button>
                    </div>
                </div>
              </div>
            </div>

            <!-- 分页 -->
            <nav aria-label="Page navigation" style="float: right;">
                <ul class="pagination">
{#                    <li><a href="#" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>#}
{#                    <li><a href="{% url 'cmdb_ui:asset_list' page_num=1 %}">1</a></li>#}
                    {{ page_html }}
{#                    <li><a href="#" aria-label="Next"><span aria-hidden="true">&raquo;</span></a></li>#}
                </ul>
            </nav>
        </div>
    </div>
{% endblock %}


{% block JavaScripts %}
    <script type="text/javascript" src="{% static 'js/common.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/list.js' %}"></script>
{% endblock %}

